apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8swithjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8swithjava
  template:
    metadata:
      labels:
        app: k8swithjava
    spec:
      containers:
        - name: k8swithjava
          image: kalyansagi/k8swithjava
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: "http"
            - containerPort: 5005
              name: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: k8swithjava
spec:
  selector:
    app: k8swithjava
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer