apiVersion: v1
kind: Service
metadata:
  name: k8swithjava
spec:
  selector:
    app: k8swithjava
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer